shoved in a confirmation and placed an excludes file for downloads archive

diff --git a/cs_downloads-archive b/cs_downloads-archive
--- a/cs_downloads-archive
+++ b/cs_downloads-archive
@@ -6,11 +6,9 @@ YELLOW='\033[0;33m'
 END='\033[0m'
 DATE_TIME=$(date +%Y%m%d_%H%M)
 
-cd ~/Downloads
-
 fail_and_quit() {
-  printf "${RED}FAILED${END}\n"
-  exit 1
+printf "${RED}FAILED${END}\n"
+exit 1
 }
 
 create_contents() {
@@ -21,9 +19,14 @@ create_contents() {
 
 create_archive() {
     printf "Creating archive...  "
-    tar --exclude="archive" -zcf "./archive/$DATE_TIME.tar.gz" ./* --remove-files || fail_and_quit
+    tar --exclude-from=".archiveignore" -zcf "./archive/$DATE_TIME.tar.gz" ./* --remove-files || fail_and_quit
     printf "${GREEN}COMPLETE${END}\n"
 }
 
-create_contents
-create_archive
+read -r -p "Are you sure you want to archive your downloads folder? [y/N] " response
+response=${response,,}
+if [[ "$response" =~ ^(yes|y)$ ]]; then
+    cd ~/Downloads
+    create_contents
+    create_archive
+fi
